ino/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chaining/', include('smart_selects.urls')),

 ] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('ino_main.urls', namespace='ino_main')),
    path('users/', include('users.urls', namespace='users')),
    prefix_default_language=False
)

handler400 = 'ino_main.views.error400'
handler404 = 'ino_main.views.error404'
handler500 = 'ino_main.views.error500'


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ino_main/urls.py
from django.urls import path

from .views import AboutView, CookieView, PrivacyView

app_name = 'ino_main'

urlpatterns = [

    path('', AboutView.as_view(), name='about'),
    path('cookie/', CookieView.as_view(), name='cookie'),
    path('privacy_policy/', PrivacyView.as_view(), name='privacy_policy'),



]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (UserRegistrationView, UserLoginView, UserProfileEditView,
                    UserProfileView, EmailVerificationView, user_delete, delete_user_image,
                    ProfilesView, QuestionnaireView, SomeProfileView, UserPasswordReset, UserPasswordResetConfirm,)
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile_edit/<int:pk>/', UserProfileEditView.as_view(), name='profile_edit'),
    path('profile/<int:id>/', UserProfileView.as_view(), name='profile'),
    path('profile_view/<int:id>/', SomeProfileView.as_view(), name='profile_view'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('questionnaire_edit/<int:pk>/', QuestionnaireView.as_view(), name='questionnaire_edit'),

    path('profiles/', ProfilesView.as_view(), name='profiles'),

    path('delete_user/<int:id>/', user_delete, name='delete_user'),
    path('delete_user_image/<int:id>/', delete_user_image, name='delete_user_image'),

    path('password_reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

]

users/models.py
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.conf import settings

from django.utils.timezone import now
from users.managers import CustomUserManager

from cities.models import Country

from datetime import date


class Hobby(models.Model):
    title = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name = 'hobby'
        verbose_name_plural = 'hobbies'

    def __str__(self):
        return f'{self.title}'


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=30, blank=True, null=True)
    first_name = models.CharField(verbose_name=_('first_name'), max_length=30)
    last_name = models.CharField(verbose_name=_('last_name'), max_length=30)
    birthdate = models.DateField(null=True, blank=True)
    gender = models.CharField(verbose_name=_('gender'), max_length=50, null=True, blank=True)
    password = models.CharField(max_length=100)
    native_language = models.CharField(verbose_name=_('native_language'), max_length=30, null=True, blank=True)
    preferred_language = models.CharField(verbose_name=_('preferred_language'), max_length=30, null=True, blank=True)
    residence_city = models.CharField(verbose_name=_('residence_city'), max_length=128, null=True, blank=True)
    native_country = models.ForeignKey(verbose_name=_('native_country'), to=Country, on_delete=models.SET_NULL,
                                       max_length=128, null=True, blank=True)
    university = models.CharField(verbose_name=_('university'), max_length=100, null=True, blank=True)
    specialty = models.CharField(verbose_name=_('specialty'), max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    hobby = models.ManyToManyField('Hobby')
    url = models.CharField(null=True, blank=True, max_length=64)
    about_yourself = models.TextField(verbose_name=_('about_yourself'), null=True, blank=True)
    remember_me = models.BooleanField(default=True)
    is_verified_email = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_user_age_ru(self):
        today = date.today()
        age = today.year - self.birthdate.year - (
                (today.month, today.day) < (self.birthdate.month, self.birthdate.day))

        if age % 10 == 1:
            return f'{age} год'
        elif age % 10 in (2, 3, 4):
            return f'{age} года'
        else:
            return f'{age} лет'

    def get_user_age_en(self):
        today = date.today()
        age = today.year - self.birthdate.year - (
                (today.month, today.day) < (self.birthdate.month, self.birthdate.day))

        if age % 10 == 1:
            return f'{age} year'
        elif age % 10 in (2, 3, 4, 5, 6, 7, 8, 9, 0):
            return f'{age} years'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def get_url(self):
        nickname = str(self.url)
        nickname = nickname.replace('@', '')
        url = f'https://t.me/{nickname}'
        return url

    def __str__(self):
        return f'Mail: {self.email}'
        # return f'Username: {self.username} | University: {self.university} | Mail: {self.email}'


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.email}'
        message = 'Для подтверждения учетной записи для {} перейдите по ссылке: {}'.format(
            self.user.email,
            verification_link,
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect

from django.conf import settings

from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView

from django.views.generic.edit import CreateView, UpdateView
from django.contrib import auth, messages
from django.contrib.auth.views import TemplateView, LoginView, PasswordResetView, PasswordResetConfirmView
from .models import User, EmailVerification, Hobby
from common.views import CommonContextMixin
from .forms import (UserLoginForm, UserRegistrationForm, UserProfileEditForm, UserQuestionnaireForm,
                    PasswordRecoveryForm, HobbyForm, UserSearchForm, NewPasswordForm)


class UserRegistrationView(CommonContextMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    title = 'INO - Регистрация'
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, "Пользователь с таким email уже существует.\nUser with this email already exists.")
        return response


class UserLoginView(CommonContextMixin, LoginView):
    template_name = 'users/login.html'
    authentication_form = UserLoginForm
    title = 'INO - Авторизация'

    def get_success_url(self):
        return reverse_lazy('users:profile_edit', args=(self.request.user.id,))

    def form_invalid(self, form):
        # Добавляем своё сообщение об ошибке в случае неверного логина или пароля
        messages.error(self.request, 'Неверный логин или пароль.\nInvalid username or password.')
        return super().form_invalid(form)

    def form_valid(self, form):
        remember_me = form.cleaned_data['remember_me']
        if not remember_me:
            self.request.session.set_expiry(0)
        else:
            self.request.session.set_expiry(settings.SESSION_COOKIE_AGE)
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)


class UserPasswordReset(PasswordResetView):
    template_name = 'users/password_reset.html'
    form_class = PasswordRecoveryForm
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset')
    from_email = settings.EMAIL_HOST_USER

    def form_valid(self, form):
        email = form.cleaned_data['email']

        try:
            user = User.objects.get(email=email)
        except:
            form.add_error('email', 'Пользователь с указанным email не найден.\nUser with this email was not found.')
            return self.form_invalid(form)

        form.save(
            subject_template_name=self.email_template_name,
            from_email=self.from_email,
            email_template_name=self.email_template_name,
            use_https=self.request.is_secure(),
            request=self.request,
        )

        messages.success(self.request, 'На указанный email было отправлено письмо для создания нового пароля.')
        return super().form_valid(form)


class UserPasswordResetConfirm(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    form_class = NewPasswordForm
    success_url = reverse_lazy('users:login')


class ProfilesView(LoginRequiredMixin, CommonContextMixin, ListView):
    model = User
    template_name = 'users/all_profiles.html'
    context_object_name = 'users'
    title = 'INO - Анкеты'
    paginate_by = 8

    @staticmethod
    def user_check(request):
        user = request.user

        conditions_not_met = []

        if user.first_name == '':
            conditions_not_met.append("имя")
        if user.last_name == '':
            conditions_not_met.append("фамилия")
        if user.gender is None:
            conditions_not_met.append("Пол")
        if user.university is None:
            conditions_not_met.append("Университет")
        if user.url is None:
            conditions_not_met.append("Ссылка")
        if user.preferred_language is None:
            conditions_not_met.append("Изучаемый язык")
        if user.native_language is None:
            conditions_not_met.append("Родной язык")
        if user.hobby is None:
            conditions_not_met.append("Интересы")
        if user.birthdate is None:
            conditions_not_met.append("Дата рождения")
        if not user.is_verified_email:
            conditions_not_met.append("Почта")

        return conditions_not_met

    def get_queryset(self):
        queryset = User.objects.exclude(
            Q(first_name='') |
            Q(last_name='') |
            Q(gender=None) |
            Q(university=None) |
            Q(native_language=None) |
            Q(url__isnull=True) |
            Q(is_verified_email=False) |
            Q(preferred_language=None) |
            Q(birthdate__isnull=True) |
            Q(hobby__isnull=True)
        )

        hobby = self.request.GET.get('hobby')
        if hobby:
            queryset = queryset.filter(hobby__title=hobby)

        preferred_language = self.request.GET.get('preferred_language')
        if preferred_language:
            queryset = queryset.filter(preferred_language=preferred_language)

        gender = self.request.GET.get('gender')
        if gender:
            queryset = queryset.filter(gender=gender)

        residence_city = self.request.GET.get('residence_city')
        if residence_city:
            queryset = queryset.filter(residence_city=residence_city)

        university = self.request.GET.get('university')
        if university:
            queryset = queryset.filter(university=university)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserSearchForm(self.request.GET)
        context['conditions'] = self.user_check(self.request)
        return context


class UserProfileEditView(LoginRequiredMixin, CommonContextMixin, UpdateView):
    model = User
    form_class = UserProfileEditForm
    template_name = 'users/profile_edit.html'
    title = 'INO - Редактирование профиля'

    def get_success_url(self):
        return reverse_lazy('users:profile_edit', args=(self.request.user.id,))

    def form_valid(self, form):
        user = User.objects.get(id=self.request.user.id)

        url = form.cleaned_data['url']
        if url.find('@') == -1 or url.find('@') != 0 or len(url) < 6:
            return self.form_invalid(form)

        image = self.request.FILES.get('image')
        if image:
            # user = form.save(commit=False)
            if image.size <= 5 * 1024 * 1024:
                # user.image = image
                user.save()
            else:
                return self.form_invalid(form)

        return super().form_valid(form)

    def form_invalid(self, form):
        user = User.objects.get(id=self.request.user.id)

        image = self.request.FILES.get('image')
        if image:
            if image.size <= 5 * 1024 * 1024:
                user.image = image
                user.save()
                return HttpResponseRedirect(reverse_lazy('users:profile_edit', args=(self.request.user.id,)))
            else:
                return super().form_invalid(form)

        return super().form_invalid(form)


class QuestionnaireView(CommonContextMixin, LoginRequiredMixin, View):
    template_name = 'users/questionnaire_edit.html'
    title = 'INO - Редактирование анкеты'

    @classmethod
    def initial_form(cls, request):
        qf = UserQuestionnaireForm(initial={
            'birthdate': request.user.birthdate,
            'gender': request.user.gender,
            'native_language': request.user.native_language,
            'preferred_language': request.user.preferred_language,
            'residence_city': request.user.residence_city,
            'native_country': request.user.native_country,
            'university': request.user.university,
            'specialty': request.user.specialty,
        })

        hf = HobbyForm(initial={
            'hobby': request.user.hobby.all(),
        })

        form_dict = {'qf': qf, 'hf': hf, 'title': cls.title}
        return form_dict

    def get(self, request, *args, **kwargs):
        forms_dict = self.initial_form(request)

        hobbies = Hobby.objects.all()

        context = {
            'hf': forms_dict['hf'],
            'qf': forms_dict['qf'],
            'hobbies': hobbies,
            'title': self.title
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        qf = UserQuestionnaireForm(request.POST)
        hf = HobbyForm(request.POST)
        user = User.objects.get(id=request.user.id)

        if qf.is_valid():
            bd = qf.cleaned_data['birthdate']
            gender = qf.cleaned_data['gender']
            native_language = qf.cleaned_data['native_language']
            preferred_language = qf.cleaned_data['preferred_language']
            native_country = qf.cleaned_data['native_country']
            residence_city = qf.cleaned_data['residence_city']
            university = qf.cleaned_data['university']
            specialty = qf.cleaned_data['specialty']

            if residence_city == '':
                user.residence_city = None
            else:
                user.residence_city = residence_city

            user.birthdate = bd
            user.gender = gender
            user.native_language = native_language
            user.preferred_language = preferred_language
            user.native_country = native_country

users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h1>Password set</h1>
<p>Your password has been set. You can <a href="{% url 'users:login' %}">log in now</a></p>
{% endblock %}

users/templates/users/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link
below:

{{protocol}}://{{domain}}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Your username,in case you've forgotten:{{ user.get_username }}

users/templates/users/profile.html
{% extends 'users/base.html' %}

{% load static %}

{% load i18n %}

{% block content %}

  <style>
    .description{
      color:var(--gray-800);
      margin:16px 0 0 0;
      word-wrap: break-word;
    }
    .item__cor {
      color: var(--grey-800);
      word-break: break-word;
    }
    .fio {
      color: var(--grey-900);
      margin: 24px 0 8px 0;
      word-wrap: break-word;
    }
    .photo-def {
      position: relative;
      border-radius: 8px;
      display: flex;
      transition: all 0.3s ease-in-out;
      cursor: default;
      width: 192px;
      height: 192px;
      margin-top: 24px;
    }
    .circle {
      padding: 2px 16px;
      font-size: var(--macro-text);
      line-height: 24px;
      color: var(--primary-color);
      border: 1px solid var(--primary-color);
      border-radius: 200px;
    }
    .user-photo {
    object-fit: cover;
    border-radius: 8px;
  
    }
    .buttonheader:hover {
      background-color: #e4e4e486;
      border-radius: 10px;
    }

    .left-part button {
      width: 196px;
      height: 38px;
      background-color: var(--primary-color);
      border: 0;
      border-radius: 4px;
      color: white;
      font-size: var(--mini-text);
      line-height: 24px;
      text-align: center;
      padding: 7px 45.5px;
      justify-content: space-between;
      margin-top: 24px;
    }
    .left-part button:hover {
      background-color: #0027da;
    }

    .left-part {
      margin: 64px 98px 24px 98px;
    }
    ul {
      padding: 0;
      margin: 0;
      list-style-type: none;
    }
   .hi2{
     border-left: 1px solid rgb(223, 223, 223); 
    }
   .my-profile-wrap {
      display: grid;
      grid-template-columns: repeat(2, 50%);
      grid-auto-flow: row;
      background-color: #f8f9fa;
      width: 1296px;
      margin-inline: auto;
      margin-top: 32px;
      border-radius: 16px;
    }
    .right-part {
      margin: 64px 100px 113px 122px;
    }
    .info{
      margin-top:32px;
    }
    @media handheld, screen and (max-width:991px) {
      .padding-interests{
        padding-bottom:32px;
      }
      .hi2{
        border-left:none;
      } 
      .fio {
        color: var(--grey-900);
        margin: 0 0 8px 0;
        word-break: break-all;
      }
      #fiolink {
        margin-left: 24px;
        margin-top: 0;
      }
      .my-profile-wrap {
        display: grid;
        grid-template-columns:100%;
        width: 93.6%;
        height: 100%;
      }
      .photo-def {
        margin-top:0;
        width: 94px;
        height: 94px;
      }
      .hi1 {
        border-right: none;
      }
      .right-part {
        margin: 0 24px 24px 24px;
      }
      .fio-photo {
        display: flex;
      }
      .edit-button {
        width: 95%;
      }
      .left-part {
        margin: 24px 24px 24px 24px;

      }
      .left-part button {
        width: 100%;
        height: 38px;
        background-color: var(--primary-color);
        border: 0;
        border-radius: 4px;
        color: white;
        font-size: var(--mini-text);
        line-height: 24px;
        text-align: center;
        padding: 7px 45.5px;
        justify-content: space-between;
        margin-top: 24px;
      }
      h2,
      h3 {
        color: #152536;
        font-size: 20px;
        line-height: auto;
        font-weight: 600;
      }
      h5 {
        color: #152536;
        font-size: 16px;
        line-height: auto;
        font-weight: 600;
      }
      .info{
        margin-top:16px;
      }
    }
  </style>
  <body>
    <nav class="navbar navbar-dark navbar-expand-lg">
      <div class="container-fluid">
        <div class="navbar-brand" href="#">
          <img class="logo_white" src="{% static 'vendor/img/logo-white.svg' %}" alt="Logo" />
        </div>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="offcanvas"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
          style="border: none; margin-right: -3%"
        >
          <span
            ><img src="{% static 'vendor/img/hamburger-md-svgrepo-com.svg' %}" style="width: 30px" alt=""
          /></span>
        </button>
        <div
          class="offcanvas offcanvas-end"
          tabindex="-1"
          id="navbarNav"
          aria-labelledby="navbarNavLabel"
        >
          <div class="offcanvas-header">
            <div class="navbar-brand">
              <img class="logo" src="{% static 'vendor/img/Logo-blue.svg' %}" alt="" />
            </div>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="offcanvas"
              aria-label="Close"
            ></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profiles' %}">{% trans "Анкеты" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' user.id %}">{% trans "Профиль" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ino_main:about' %}">{% trans "О проекте" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <form id="language-form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select id="language-select" name="language" onchange="changeLanguage()"
                    class="lang-navbar">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" style="display: none;">
</form>

<script>
    const languageSelect = document.getElementById('language-select');
    const languageForm = document.getElementById('language-form');

    languageSelect.addEventListener('change', () => {
        languageForm.submit();
    });
</script>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="my-profile-wrap">
      <div class="hi1">
        <div class="left-part">
          <div class="fio-photo">
            <div class="photo-def">
              <img class="user-photo" src="{% if user.image %} {{user.image.url}}
              {% else %} {% static 'vendor/img/User-profile.svg' %} {% endif %}" alt="" alt="" />
            </div>
            <div id="fiolink">
              <h2 class="fio">{{ user.first_name }} {{ user.last_name }}</h2>
              <p class="mini-text" style="color: var(--body-color)">
                {% if user.url is not None %}
                {{ user.get_url }}
                {% else %}
                {% trans 'Отсутствует' %}
                {% endif %}
              </p>
            </div>
          </div>
          <p
            class="mini-text description"
          >
          {% if user.about_yourself is not None %}
          {{ user.about_yourself }}
          {% else %}
          {% trans 'Описание отсутствует' %}
          {% endif %}
          </p>
          <button onclick="window.location.href='{% url 'users:questionnaire_edit' user.id %}'"
            >
            {% trans "Редактировать" %}
         </button>
        </div>
     </div>
     <div class="hi2">
        <div class="right-part">
          <h3 class="m-o" style="color: var(--gray-800)">{% trans "Анкета" %}</h3>
          <ul class="info">
            <li class="d-flex body-text">
              <div style="width:63.94px">
                <span class="item__label" style="color: var(--body-color)"
                  >{% trans "Возраст" %}</span
                >
              </div>
              <span class="item__cor" style="margin-left: 132px">{% if user.birthdate is not None %}
                {% if LANGUAGE_CODE == 'en' %}
                {{ user.get_user_age_en }}
                {% else %}
                {{ user.get_user_age_ru }}
                {% endif %}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span>
            </li>
            <li class="d-flex body-text" style="margin-top: 8px">
              <div style="width:55.78px">
                <span class="item__label" style="color: var(--body-color)"
                  >{% trans "Пол" %}</span
                >
              </div>
              <span class="item__cor" style="margin-left: 140px">{% if user.gender is not None %}
                {{ user.gender }}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span>
            </li>
            <li class="d-flex body-text" style="margin-top: 8px">
              <div style="width:159.48px">
                <span class="item__label" style="color: var(--body-color)"
                  >{% trans "Родной язык" %}</span
                >
              </div>
              <span class="item__cor" style="margin-left: 36px">{% if user.native_language is not None %}
                {{ user.native_language }}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span>
            </li>
            <li class="d-flex body-text" style="margin-top: 8px">
              <div style="width:139.39px">
                <span
                  class="item__label body-text"
                  style="color: var(--body-color)"
                  >{% trans "Изучаемый язык" %}</span
                >
              </div>
              <span class="item__cor body-text" style="margin-left: 56.25px"
                >{% if user.preferred_language is not None %}
                {{ user.preferred_language }}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span
              >
            </li>
          </ul>

          <h5 style="margin-top: 24px">Личная информация</h5>
          <ul>
            <li class="d-flex body-text" style="margin-top: 16px">
              <div style="width:115.83px">
                <span class="item__label" style="color: var(--body-color)"
                  >{% trans "Родная страна" %}</span
                >
              </div>
              <span class="item__cor" style="margin-left: 80px">{% if user.native_country is not None %}
                {{ user.native_country }}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span>
            </li>
            <li class="d-flex body-text" style="margin-top: 8px">
              <div style="width:115.83px">
                <span class="item__label" style="color: var(--body-color)"
                  >{% trans "Город проживания" %}</span
                >
              </div>
              <span class="item__cor" style="margin-left: 80px">
                {% if user.residence_city is not None %}
                {{ user.residence_city }}
                {% else %}
                {% trans 'Отсутствует' %}
                {% endif %}
              </span>
            </li>
          </ul>
          <h5 style="margin-top: 24px">{% trans "Образование" %}</h5>
          <ul>
            <li class="d-flex" style="margin-top: 16px">
              <div style="min-width: 75.78px">
                <span
                  class="item__label body-text"
                  style="color: var(--body-color)"
                  >{% trans "ВУЗ" %}</span
                >
              </div>
              <span class="item__cor body-text" style="margin-left: 119.8px"
                >{% if user.university is not None %}
                {{ user.university }}
              {% else %}
              {% trans "Отсутствует" %}
              {% endif %}</span
              >
            </li>
            <li class="d-flex" style="margin-top: 8px">
              <div style="min-width: 123px">
                <span
                  class="item__label body-text"
                  style="color: var(--body-color)"
                  >{% trans "Специальность" %}</span
                >
              </div>
              <span class="item__cor body-text" style="margin-left: 73px"
                >{% if user.specialty %}
                {{ user.specialty }}
                 {% else %}
                {% trans "Отсутствует" %}
                {% endif %}
              </span>
            </li>
          </ul>
          <div class="padding-interests">
            <div class="d-flex">
              <h5 style="color: var(--gray-800); margin: 24px 0 16px 0">
                {% trans "Интересы" %}
              </h5>
            </div>
            <div class="d-flex flex-row mb-2 gap-2 flex-wrap">
              {% for hobby in user.hobby.all %}
                <span class="circle">{{ hobby.title }}</span>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  {% endblock %}