ino/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chaining/', include('smart_selects.urls')),

 ] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('ino_main.urls', namespace='ino_main')),
    path('users/', include('users.urls', namespace='users')),
    prefix_default_language=False
)

handler400 = 'ino_main.views.error400'
handler404 = 'ino_main.views.error404'
handler500 = 'ino_main.views.error500'


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ino_main/urls.py
from django.urls import path

from .views import AboutView, CookieView, PrivacyView

app_name = 'ino_main'

urlpatterns = [

    path('', AboutView.as_view(), name='about'),
    path('cookie/', CookieView.as_view(), name='cookie'),
    path('privacy_policy/', PrivacyView.as_view(), name='privacy_policy'),



]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (UserRegistrationView, UserLoginView, UserProfileEditView,
                    UserProfileView, EmailVerificationView, user_delete, delete_user_image,
                    ProfilesView, QuestionnaireView, SomeProfileView, UserPasswordReset, UserPasswordResetConfirm,)
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile_edit/<int:pk>/', UserProfileEditView.as_view(), name='profile_edit'),
    path('profile/<int:id>/', UserProfileView.as_view(), name='profile'),
    path('profile_view/<int:id>/', SomeProfileView.as_view(), name='profile_view'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('questionnaire_edit/<int:pk>/', QuestionnaireView.as_view(), name='questionnaire_edit'),

    path('profiles/', ProfilesView.as_view(), name='profiles'),

    path('delete_user/<int:id>/', user_delete, name='delete_user'),
    path('delete_user_image/<int:id>/', delete_user_image, name='delete_user_image'),

    path('password_reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

]

ino_main/models.py
from django.db import models


class FeedBack(models.Model):
    code = models.UUIDField(unique=True)
    name = models.CharField(max_length=32)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f'FeedBack object {self.code}'

ino_main/forms.py
from django import forms


class FeedBackForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mini-text', 'placeholder': 'Введите имя', 'type': 'mail', 'id': 'mail', 'rows': '5',
    }), required=False)

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control mini-text', 'placeholder': 'Введите почту', 'type': 'mail', 'rows': '5',
    }))

    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control mini-text', 'placeholder': 'Введите текст', 'rows': '5',
    }))

    class Meta:
        fields = ['name', 'email', 'message']

ino_main/views.py
import uuid

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from common.views import CommonContextMixin

from ino_main.forms import FeedBackForm
from ino_main.models import FeedBack
from users.models import User


class AboutView(CommonContextMixin, FormView):
    template_name = 'ino_main/about.html'
    form_class = FeedBackForm
    title = 'INO - О нас'
    success_url = reverse_lazy('ino_main:about')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        if User.objects.filter(email=email).exists():
            feedback = FeedBack(code=uuid.uuid4(), name=name, email=email, message=message)
            feedback.save()

            # Отправка письма
            send_mail(
                subject='Feedback',
                message=f'Name: {name}\nEmail: {email}\nMessage: {message}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER],
                fail_silently=False,
            )
        return super().form_valid(form)


class CookieView(CommonContextMixin, TemplateView):
    template_name = 'ino_main/cookies.html'
    title = 'INO - Cookie'


class PrivacyView(CommonContextMixin, TemplateView):
    template_name = 'ino_main/privacy.html'
    title = 'INO - Политика конфиденциальности'


def error400(request, exception):
    return render(request, 'ino_main/error400.html', {})


def error404(request, exception):
    return render(request, 'ino_main/error404.html', {})


def error500(request, exception=None):
    return render(request, 'ino_main/error500.html', {})


def technical_break(request, exception):
    return render(request, 'ino_main/technical_break.html', {})

ino_main/templates/ino_main/cookies.html
{% extends 'users/base.html' %} {% load static %} {% load i18n %} {% block content %}
  <style>
    .up {
      padding: 48px 0 20px 0;
    }
    .container {
      width: 1296px;
    }
    .politics {
      width: 90%;
      margin-left: 16px;
    }
    .arrow {
      margin-top: 7px;
    }
    @media handheld, screen and (max-width:991px) {
      .container {
        width: 90%;
      }
      .arrow {
        margin-top: 0;
      }
      h2 {
        color: #152536;
        font-size: 20px;
        line-height: auto;
        font-weight: 600;
      }
      .body-text {
        font-size: 14px;
        line-height: 24px;
        font-weight: 400;
      }
      .up {
        padding: 30px 0 10px 0;
      }
    }
  </style>
  <body>
    <nav class="navbar navbar-dark navbar-expand-lg">
        <div class="container-fluid">
          <div class="navbar-brand" href="#">
            <img class="logo_white" src="{% static 'vendor/img/logo-white.svg' %}" alt="Logo" />
          </div>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
            style="border: none; margin-right: -3%"
          >
            <span
              ><img src="{% static 'vendor/img/hamburger-md-svgrepo-com.svg' %}" style="width: 30px" alt=""
            /></span>
          </button>
          <div
            class="offcanvas offcanvas-end"
            tabindex="-1"
            id="navbarNav"
            aria-labelledby="navbarNavLabel"
          >
            <div class="offcanvas-header">
              <div class="navbar-brand">
                <img class="logo" src="{% static 'vendor/img/Logo-blue.svg' %}" alt="" />
              </div>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profiles' %}">{% trans "Анкеты" %}</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profile' user.id %}">{% trans "Профиль" %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">{% trans "Профиль" %}</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'ino_main:about' %}">{% trans "О проекте" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <form id="language-form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select id="language-select" name="language" class="lang-navbar">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" style="display: none;">
</form>

<script>
    const languageSelect = document.getElementById('language-select');
    const languageForm = document.getElementById('language-form');

    languageSelect.addEventListener('change', () => {
        languageForm.submit();
    });
</script>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    <main style="background-color: #f7f6ff">
        <div class="d-flex container up">
            <div class="arrow">
                <input
                  type="image"
                  src="{% static 'vendor/img/arrow-left.svg' %}"
                  onclick="history.back();"
                />
              </div>
            <div class="politics">
              <h2>{% trans "Политика использования cookies" %}</h2>
            </div>
          </div>
                <div class="container">
                  <p class="body-text">
                    <strong>{% trans "Уведомление об использовании cookie файлов." %}</strong> <br />{% blocktrans %}Наш
                    сайт, как и большинство других, использует файлы cookie и другие
                    похожие технологии (пиксельные тэги и т.п.), чтобы предоставлять
                    услуги, наиболее отвечающие Вашим интересам и потребностям, а также
                    собирать статистическую и маркетинговую информацию для анализа и
                    совершенствования наших услуг и сайтов. При использовании данного
                    сайта, вы подтверждаете свое согласие на использование файлов cookie и
                    других похожих технологий в соответствии с настоящим Уведомлением.
                    Если Вы не согласны, чтобы мы использовали данный тип файлов, Вы
                    должны соответствующим образом установить настройки Вашего браузера
                    или не использовать наш сайт. Обращаем Ваше внимание на то, что при
                    блокировании или удалении cookie файлов, мы не можем гарантировать
                    корректную работу нашего сайта в Вашем браузере. Cookie файлы, которые
                    сохраняются через веб-сайт, не содержат сведений, на основании которых
                    можно Вас идентифицировать.{% endblocktrans %}<br /><br /><strong
                      >{% trans "Что такое файл cookie и другие похожие технологии." %} </strong
                    ><br />
                    {% blocktrans %}Файл cookie представляет собой небольшой текстовый файл, сохраняемый
                    на вашем компьютере, смартфоне или другом устройстве, которое Вы
                    используете для посещения интернет-сайтов. Некоторые посещаемые Вами
                    страницы могут также собирать информацию, используя пиксельные тэги и
                    веб-маяки, представляющие собой электронные изображения, называемые
                    одно-пиксельными (1×1) или пустыми GIF-изображениями. Файлы cookie
                    могут размещаться на вашем устройстве нами («собственные» файлы
                    cookie) или другими операторами (файлы cookie «третьих лиц»). Мы
                    используем два вида файлов cookie на сайте: «cookie сессии» и
                    «постоянные cookie». Cookie сессии — это временные файлы, которые
                    остаются на устройстве пока вы не покинете сайт. Постоянные cookie
                    остаются на устройстве в течение длительного времени или пока вы
                    вручную не удалите их (как долго cookie останется на вашем устройстве
                    будет зависеть от продолжительности или «времени жизни» конкретного
                    файла и настройки вашего браузера).{% endblocktrans %}<br /><br /><strong
                      >{% trans "Cookie файлы бывают различных типов:" %} </strong
                    ><br />
                    {% blocktrans %}Необходимые. Эти файлы нужны для обеспечения правильной работы сайта,
                    использования его функций. Отключение использования таких файлов
                    приведет к падению производительности сайта, невозможности
                    использовать его компоненты и сервисы. Файлы cookie, относящиеся к
                    производительности, эффективности и аналитике. Данные файлы позволяют
                    анализировать взаимодействие посетителей с сайтом, оптимизировать
                    содержание сайта, измерять эффективность рекламных кампаний,
                    предоставляя информацию о количестве посетителей сайта, времени его
                    использования, возникающих ошибках.{% endblocktrans %}<br />
                    {% blocktrans %}Функциональные файлы cookie запоминают пользователей, которые уже
                    заходили на наш сайт, их индивидуальные параметры (такие как язык и
                    регион, например) и предпочтения, и помогают индивидуализировать
                    содержание сайта. Рекламные файлы cookie определяют, какие сайты Вы
                    посещали и как часто, какие ссылки Вы выбирали, что позволяет
                    показывать Вам рекламные объявления, которые заинтересуют именно Вас.
                    Электронная почта. Мы также можем использовать технологии, позволяющие
                    отслеживать, открывали ли вы, прочитали или переадресовывали
                    определенные сообщения, отправленные нами на вашу электронную почту.
                    Это необходимо, чтобы сделать наши средства коммуникации более
                    полезными для пользователя. Если вы не желаете, чтобы мы получали
                    сведения об этом, вам нужно аннулировать подписку посредством ссылки
                    «Отписаться» («Unsubscribe»), находящейся внизу соответствующей
                    электронной рассылки. Кнопки доступа к социальным сетям. Они
                    используются для того, чтобы пользователи могли поделиться ссылкой на
                    страницу в социальных сетях или сделать электронную закладку. Данные
                    кнопки являются ссылками на веб-сайты социальных сетей, принадлежащих
                    третьим лицам, которые, в свою, очередь могут фиксировать информацию о
                    вашей активности в интернете, в том числе на нашем сайте. Пожалуйста,
                    ознакомьтесь с соответствующими условиями использования и политикой
                    конфиденциальности таких сайтов для понимания того, как они используют
                    ваши данные, и того, как можно отказаться от использования ими ваших
                    данных или удалить их. Сторонние веб-сервисы. Иногда на данном сайте
                    мы используем сторонние веб-сервисы. Например, для отображения тех или
                    иных элементов (изображения, видео, презентации и т. п.), организации
                    опросов и т. п. Как и в случае с кнопками доступа к социальным сетям,
                    мы не можем препятствовать сбору этими сайтами или внешними доменами
                    информации о том, как вы используете содержание сайта.{% endblocktrans %}<br /><br /><strong
                      >{% trans "Как управлять файлами cookie?" %}</strong
                    ><br />{% blocktrans %}Большинство интернет-браузеров изначально настроены на
                    автоматический прием файлов cookie. В любое время Вы можете изменить
                    настройки вашего браузера таким образом, чтобы блокировать файлы
                    cookie или предупреждать вас о том, когда они будут отправляться к вам
                    на устройство (обратитесь к руководству использования конкретного
                    браузера). Отключение файлов cookie может повлиять на Вашу работу в
                    интернете. Если вы используете несколько устройств и (или) браузеров
                    для доступа в интернет, соответствующие настройки должны быть изменены
                    в каждом из них.{% endblocktrans %} <br /><br /><strong>{% trans "Заключительные положения:" %}</strong
                    ><br />
                    {% blocktrans %}По собственному усмотрению мы можем периодически изменять настоящее
                    Уведомление. {% endblocktrans %}<br /> {% blocktrans %} "По возникающим вопросам с нами можно связаться,
                    используя контакты, размещенные на нашем сайте.{% endblocktrans %}
                  </p>
                </div>
              </main>
            </body>
            {% endblock %}

ino_main/templates/ino_main/error400.html
{% extends 'users/base.html' %} {% load static %} {% load i18n %} {% block content %}
<style>
  @media handheld, screen and (max-width:768px) {
    h1 {
      font-size: 24px;
      text-align: center;
    }
    .lead-text {
      font-size: 16px;
      line-height: 28px;
      font-weight: 400;
      text-align: center;
    }
  }
</style>
<body style="background-color: #f1f2ff">
  <nav class="navbar navbar-dark navbar-expand-lg">
    <div class="container-fluid">
      <div class="navbar-brand" href="#">
        <img class="logo_white" src="{% static 'vendor/img/logo-white.svg' %}" alt="Logo" />
      </div>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="offcanvas"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        style="border: none; margin-right: -3%"
      >
        <span
          ><img src="{% static 'vendor/img/hamburger-md-svgrepo-com.svg' %}" style="width: 30px" alt=""
        /></span>
      </button>
      <div
        class="offcanvas offcanvas-end"
        tabindex="-1"
        id="navbarNav"
        aria-labelledby="navbarNavLabel"
      >
        <div class="offcanvas-header">
          <div class="navbar-brand">
            <img class="logo" src="{% static 'vendor/img/Logo-blue.svg' %}" alt="" />
          </div>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
          ></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:profiles' %}">{% trans "Анкеты" %}</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profile' user.id %}">{% trans "Профиль" %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">{% trans "Профиль" %}</a>
                </li>
                {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ino_main:about' %}">{% trans "О проекте" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <form id="language-form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select id="language-select" name="language" class="lang-navbar">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" style="display: none;">
</form>

<script>
    const languageSelect = document.getElementById('language-select');
    const languageForm = document.getElementById('language-form');

    languageSelect.addEventListener('change', () => {
        languageForm.submit();
    });
</script>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="pid">
    <div class="text">
      <h1>Error 400</h1>
      <text class="lead-text">
        {% trans "Плохой запрос. Попробуйте перезагрузить" %}<br />
        {% trans "страницу или проверить введённый URL-адрес." %}
      </text>
    </div>
    <div class="pid2">
      <img class="error_image" src="{% static 'vendor/img/error.svg' %}" alt="" />
    </div>
  </div>
</body>
{% endblock %}

ino_main/templates/ino_main/error403.html
{% extends 'users/base.html' %} {% load static %} {% load i18n %} {% block content %}
<style>
  @media handheld, screen and (max-width:768px) {
    h1 {
      font-size: 24px;
      text-align: center;
    }
    .lead-text {
      font-size: 16px;
      line-height: 28px;
      font-weight: 400;
      text-align: center;
    }
  }
</style>
<body style="background-color: #f1f2ff">
  <nav class="navbar navbar-dark navbar-expand-lg">
    <div class="container-fluid">
      <div class="navbar-brand" href="#">
        <img class="logo_white" src="{% static 'vendor/img/logo-white.svg' %}" alt="Logo" />
      </div>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="offcanvas"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        style="border: none; margin-right: -3%"
      >
        <span
          ><img src="{% static 'vendor/img/hamburger-md-svgrepo-com.svg' %}" style="width: 30px" alt=""
        /></span>
      </button>
      <div
        class="offcanvas offcanvas-end"
        tabindex="-1"
        id="navbarNav"
        aria-labelledby="navbarNavLabel"
      >
        <div class="offcanvas-header">
          <div class="navbar-brand">
            <img class="logo" src="{% static 'vendor/img/Logo-blue.svg' %}" alt="" />
          </div>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
          ></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:profiles' %}">{% trans "Анкеты" %}</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profile' user.id %}">{% trans "Профиль" %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">{% trans "Профиль" %}</a>
                </li>
                {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ino_main:about' %}">{% trans "О проекте" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <form id="language-form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select id="language-select" name="language" class="lang-navbar">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" style="display: none;">
</form>

<script>
    const languageSelect = document.getElementById('language-select');
    const languageForm = document.getElementById('language-form');

    languageSelect.addEventListener('change', () => {
        languageForm.submit();
    });
</script>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="pid">
    <div class="text">
      <h1>Error 403</h1>
      <text class="lead-text">
        {% trans "Доступ запрещен. Возможно, не загружен" %}<br />
        {% trans "индексный файл или неправильно указаны" %}<br />
        {% trans "права на него." %}
      </text>
      <div>
        <button type="button" class="btn btn-primary exit">{% trans "Назад" %}</button>
      </div>
    </div>
    <div class="pid2">
      <img class="error_image" src="/static/vendor/img/error.svg" alt="" />
    </div>
  </div>
</body>
{% endblock %}

ino_main/templates/ino_main/error404.html
{% extends 'users/base.html' %} {% load static %} {% load i18n %} {% block content %}
<style>
  @media handheld, screen and (max-width:768px) {
    h1 {
      font-size: 24px;
      text-align: center;
    }
    .lead-text {
      font-size: 16px;
      line-height: 28px;
      font-weight: 400;
      text-align: center;
    }
  }
</style>
<body style="background-color: #f1f2ff">
  <nav class="navbar navbar-dark navbar-expand-lg">
    <div class="container-fluid">
      <div class="navbar-brand" href="#">
        <img class="logo_white" src="{% static 'vendor/img/logo-white.svg' %}" alt="Logo" />
      </div>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="offcanvas"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        style="border: none; margin-right: -3%"
      >
        <span
          ><img src="{% static 'vendor/img/hamburger-md-svgrepo-com.svg' %}" style="width: 30px" alt=""
        /></span>
      </button>
      <div
        class="offcanvas offcanvas-end"
        tabindex="-1"
        id="navbarNav"
        aria-labelledby="navbarNavLabel"
      >
        <div class="offcanvas-header">
          <div class="navbar-brand">
            <img class="logo" src="{% static 'vendor/img/Logo-blue.svg' %}" alt="" />
          </div>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
          ></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:profiles' %}">{% trans "Анкеты" %}</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profile' user.id %}">{% trans "Профиль" %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">{% trans "Профиль" %}</a>
                </li>
                {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ino_main:about' %}">{% trans "О проекте" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <form id="language-form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select id="language-select" name="language" class="lang-navbar">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go" style="display: none;">
</form>

<script>
    const languageSelect = document.getElementById('language-select');
    const languageForm = document.getElementById('language-form');

    languageSelect.addEventListener('change', () => {
        languageForm.submit();
    });
</script>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="pid">
    <div class="text">
      <h1>Error 404</h1>
      <text class="lead-text">
        {% trans "Страница не найдена. Возможно она была" %}<br />
        {% trans "перемещена или временно недоступна." %}
      </text>
      <div>
        <button type="button" class="btn btn-primary exit" onclick="history.back()">{% trans "Назад" %}</button>
      </div>
    </div>
    <div class="pid2">
      <img class="error_image" src="{% static 'vendor/img/error.svg' %}" alt="" />
    </div>
  </div>
</body>
{% endblock %}